name: AI HUD Robot System

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
        continue-on-error: true

      - name: Create dist folder
        run: mkdir -p dist

      ###################################################
      # 🐍 Generate Contribution Snake
      ###################################################

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      ###################################################
      # 🤖🔥 Generate HUD Robot vs Snake
      ###################################################

      - name: Generate AI HUD Animation
        run: |
          cat <<'EOF' > dist/ai-hud-system.svg
          <svg xmlns="http://www.w3.org/2000/svg"
               width="1000"
               height="350"
               viewBox="0 0 1000 350">

          <style>

          /* Background HUD grid */
          .grid line {
            stroke:#00ffcc;
            stroke-width:0.3;
            opacity:0.2;
            animation: gridMove 8s linear infinite;
          }

          @keyframes gridMove {
            from { transform:translateY(0px); }
            to { transform:translateY(20px); }
          }

          /* Robot movement */
          .robot {
            animation: walk 8s infinite linear;
          }

          @keyframes walk {
            0% { transform:translateX(0px); }
            50% { transform:translateX(700px); }
            100% { transform:translateX(0px); }
          }

          /* Laser */
          .laser {
            stroke:#ff0033;
            stroke-width:4;
            stroke-dasharray:10;
            animation:shoot 0.4s infinite linear;
          }

          @keyframes shoot {
            from { stroke-dashoffset:20; opacity:1; }
            to { stroke-dashoffset:0; opacity:0.3; }
          }

          /* Radar pulse */
          .radar circle {
            fill:none;
            stroke:#00ffcc;
            stroke-width:2;
            opacity:0.5;
            animation:pulse 2s infinite;
          }

          @keyframes pulse {
            0% { r:10; opacity:1; }
            100% { r:60; opacity:0; }
          }

          /* Targeting reticle */
          .target {
            stroke:#00ffcc;
            stroke-width:2;
            fill:none;
            animation:spin 4s linear infinite;
            transform-origin:center;
          }

          @keyframes spin {
            from { transform:rotate(0deg); }
            to { transform:rotate(360deg); }
          }

          </style>


          <!-- HUD GRID -->
          <g class="grid">
            <line x1="0" y1="50" x2="1000" y2="50"/>
            <line x1="0" y1="100" x2="1000" y2="100"/>
            <line x1="0" y1="150" x2="1000" y2="150"/>
            <line x1="0" y1="200" x2="1000" y2="200"/>
            <line x1="0" y1="250" x2="1000" y2="250"/>
          </g>

          <!-- Contribution Snake -->
          <image href="snake.svg"
                 x="0"
                 y="80"
                 width="1000"
                 height="200"/>

          <!-- Robot -->
          <g class="robot">

            <!-- head -->
            <rect x="50" y="100"
                  width="60"
                  height="60"
                  rx="10"
                  fill="#00ffcc"/>

            <!-- eye -->
            <circle cx="95"
                    cy="130"
                    r="6"
                    fill="red"/>

            <!-- body -->
            <rect x="65"
                  y="160"
                  width="30"
                  height="70"
                  fill="#00ffaa"/>

            <!-- laser -->
            <line x1="110"
                  y1="130"
                  x2="900"
                  y2="130"
                  class="laser"/>

          </g>

          <!-- Explosion -->
          <circle cx="900"
                  cy="130"
                  r="10"
                  fill="#ff0033">

            <animate attributeName="r"
                     values="5;20;5"
                     dur="0.6s"
                     repeatCount="indefinite"/>

            <animate attributeName="opacity"
                     values="1;0.2;1"
                     dur="0.6s"
                     repeatCount="indefinite"/>

          </circle>

          <!-- Radar -->
          <g class="radar">
            <circle cx="850" cy="50"/>
          </g>

          <!-- Targeting HUD -->
          <circle cx="900"
                  cy="130"
                  r="40"
                  class="target"/>

          </svg>
          EOF


      ###################################################
      # Commit and Push
      ###################################################

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/*.svg
          git commit -m "Update AI HUD animation" || echo "No changes"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
