name: GitBoard
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate dashboard
        uses: LegedsDaD/GitBoard@main
        with:
          username: LegedsDaD
          template: Quantum Forge
          theme: dark
          output: assets/my_dashboard.svg
          readme: README.md
          prefer_txt: "true"
